### ISSUE TITLE
Can one write a type stable getfield method?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataStreams.jl#22]
It seems to me that the current design effectively prohibits a type stable implementation of the `getfield` method, which would probably have huge performance implications? Or maybe I'm wrong and missing something obvious?

My implementation of the `getfield` method in Query is [here](https://github.com/davidanthoff/Query.jl/blob/datastreams-sink/src/sinks/sink_datastream_source.jl#L52). Of course the return type of that function is type stable, but the line with the return statement is not because the value returned from the expression `source.current_val[col]` (i.e. the value that is then fed into the `convert` call that is triggered by the type annotation) is not type stable. I don't really see right now how one could ever implement a type stable version of this, as long as the column index is passed as an argument of the function...

**Comment by quinnj** [comment]
The definition of `Data.getfield` that should be implemented is
```julia
Data.getfield{T}(::MyPkg.Source, ::Type{T}, row, col) => T
```
with a big emphasis on the `Type{T}` argument. Because we're passing the expected type into the method, a new method will be compiled for different instances of `T`. This is what allows `Data.getfield` to be type stable; for each instance of `T`, a separate `Data.getfield` method will be called that will return an argument of type `T`.

Hopefully that makes sense?

**Comment by quinnj** [comment]
The definition of `Data.getfield` that should be implemented is
```julia
Data.getfield{T}(::MyPkg.Source, ::Type{T}, row, col) => T
```
with a big emphasis on the `Type{T}` argument. Because we're passing the expected type into the method, a new method will be compiled for different instances of `T`. This is what allows `Data.getfield` to be type stable; for each instance of `T`, a separate `Data.getfield` method will be called that will return an argument of type `T`.

Hopefully that makes sense?

**Comment by davidanthoff** [comment]
Sure, I can make the return value type stable that way, but in the method itself, there will almost certainly still be a type instability, right? E.g., in my case I have something like a tuple that holds the column values, and then depending on the ``col`` argument I will extract the right element from the tuple, say like this:
````julia
Data.getfield{T}(::MyPkg.Source, ::Type{T}, row, col)
    return convert(T, data[col])
end
````
So the return type of this function is type stable, but not the method body itself...

**Comment by quinnj** [comment]
Well yeah, that's tale as old as time man. That's what DataFrames has been wrestling with for years now. What works here, i.e. the DataStreams solution to this problem, is making the user pass the `Type{T}` in with the call to `Data.getfield`. This allows callers to ensure type stability on the calling side because they know that when passing in a `T`, they get back out a `T`. For example, the DataFrames `Data.stream!` code looks like:
```julia
for row = 1:rows
            for col = 1:cols
                Data.getfield!(source, types[col], columns[col], row, col)
            end
        end
```
with `Data.getfield!` defined like
```julia
function getfield!{T}(source, ::Type{T}, dest, row, col)
    @inbounds dest[row] = Data.getfield(source, T, row, col)
    return
end
```
note how the type `T` and destination array `dest` are extracted in my inner loop, but immediately passed to `Data.getfield!`, which now can specialize methods depending on `T` (with `dest` being essentially `Vector{T}`). This ends up being quite type-stable because we're utilizing these "kernel type" specializations. The calls to `types[col]` and `columns[col]` are obviously not type stable, but within the function scope where julia doesn't have their type information (the inner loop), it doesn't have to do anything with them anyway. They're immediately passed on to these "type stable" kernel functions that can operate type safely.

**Comment by davidanthoff** [comment]
Well the real problem seems to be the implementation of ``Data.getfield`` and ``Data.getcolumn`` [here](https://github.com/JuliaData/DataStreams.jl/blob/master/src/DataStreams.jl#L169). Both are not type stable...

I get around all the type stability problems in [Query](https://github.com/davidanthoff/Query.jl) (even for DataFrames) by always representing one row as a [named tuple](https://github.com/blackrock/NamedTuples.jl) and only ever looping over rows in functions that deal with data. There are some loops over columns, but they are all confined to the code-generation part of generated functions, so they never run very often. The end result is that if you e.g. query a DataFrame, reshape it and then collect it into a new DataFrame, there is not a single type instability in the whole code ever.

I think what I'll try is to write an experimental CSV writer that plugs into the Query type interface and will take a look what performance difference that makes relative to the DataStreams design. For now I was just wondering whether I missed something obvious :)

**Comment by quinnj** [comment]
Thanks for pointing out the type instability; they used to be type stable, but with the integration of CategoricalArrays, I relaxed the type strictness to get things working, but forgot to go back and correct it. I've fixed the type instability locally and will push soon. There's still a type instability in Feather with CategoricalArrays as well.

**Comment by davidanthoff** [comment]
So I added a CSV writer to [Query](https://github.com/davidanthoff/Query.jl) that uses the streaming protocol from [Query](https://github.com/davidanthoff/Query.jl). I then compared the performance of writing a ``DataFrame`` with 10 million rows and three columns to a csv file using [Query](https://github.com/davidanthoff/Query.jl) and [CSV.jl](https://github.com/JuliaData/CSV.jl). I used the commit from DataStreams that has the fix for the type instability (i.e. 7ef58fb). As far as I can tell my writer does exactly the same things as the [CSV.jl](https://github.com/JuliaData/CSV.jl) writer, so functionality wise they should be equivalent (modulo support for Nullables and DateTime, but I don't think that can explain the performance differences).

The DataStreams based version is 3 times slower than the [Query](https://github.com/davidanthoff/Query.jl) based version (15s vs 5s). I don't really know whether the root cause for that is to be found in the type instability that is still there in ``Data.getcolumn`` or something else, but the difference seems significant enough to be a potential problem. I do know that the [Query](https://github.com/davidanthoff/Query.jl) way of streaming data is completely type stable, end-to-end, so maybe that could be a foundation for data streaming that could be more performant?

The code that compares performance is [here](https://github.com/davidanthoff/Query.jl/blob/sink_csv/example/21-csvsink.jl). It should work if you use the master version of [Query](https://github.com/davidanthoff/Query.jl).

**Comment by quinnj** [comment]
The "type instability" fix should affect CSV writing at all; that code lives solely in CSV.jl. I haven't spent a ton of time optimizing CSV writing, to be honest, so I'm not surprised it's not super efficient. Definitely on my list to dig into; thanks for the report.

**Comment by davidanthoff** [comment]
Did you mean "The 'type instability' fix shouldn't affect CSV writing at all"? It does affect performance, because the CSV reader needs to get its data from the DataFrame source, and that is slow with the type instability in the ``Data.getcolumn`` method for DataFrames.

The point of my code is not to show that the CSV writing code in CSV.jl is slow, what I'm really worried about is that the way the field-based streaming interface is designed right now, I can't figure out how to write a type-stable source, and that would essentially mean that we could never get the highest performance in these kind of scenarios with the current design...

**Comment by davidanthoff** [comment]
One more question: which of the sinks would you consider the most optimized? I'd like to compare performance of streaming a DataFrame to some sink for the interface in DataStreams and the one in Query so see whether the interface is a bottleneck or not (I might be wrong). To do that I would need some DataStream source/sink combination that uses the field-based interface and that you think is highly optimized.

**Comment by quinnj** [comment]
The DataStreams interface has further evolved over the last few weeks and is more type stable overall. This is partly due to creating a formal Data.Sink interface that exists in addition to the Data.Source interface. The DataStreams package itself now implements the sole `Data.stream!` methods and can ensure type stability to the extent that Sources/Sinks can support it. I'm sure there are still some corner cases that can be improved, but the consistency across the ecosystem is maturing greatly.

I'd certainly love to dig into specific issues now that the framework has hit a "0.1" release.
