### ISSUE TITLE
The fallback methods for Data.schema seem wrong

### ISSUE THREAD

**Issue by davidanthoff** [JuliaData/DataStreams.jl#23]
In particular, this line

https://github.com/JuliaData/DataStreams.jl/blob/master/src/DataStreams.jl#L162

means that if a ``Source`` defines a simple ``Data.schema(::MyPkg.Source)`` method, that method will never be called. For a field based Source, instead this

https://github.com/JuliaData/DataStreams.jl/blob/master/src/DataStreams.jl#L107

will be called, which in turn requires a ``Data.schema(source, Data.Column)`` to be defined for the Source.

All these fallback methods seem incorrect and inconsistent with the documentation. It seems to me they should all go, and all that would be needed is ``Data.schema(::MyPkg.Source)``?

**Comment by quinnj** [comment]
No, certain sources need to provide a different schema based on whether they're in a Field or Column-based streaming situation (e.g. DataFrames), hence the need for #L162 you mentioned above. This was the only sensible way for things to fall out from that since it'd be a pain to require every Source that happens to support both Field & Column streaming to define 2 different `Data.schema` methods, particularly when `Data.schema(source, ::Type{Data.Field})` can be defined automatically.

I agree it's not ideal, but I'm not sure there's a cleaner solution out there. I think the docs could certainly be improved; I'm thinking of making the "if you want to be a Field-based Source" and "if you want to be a Column-based Source" sections and making them more prominent along with emphasis that `Data.schema` needs to explicitly say what type of `Data.StreamType` you support.

Certainly open to other ideas here.

**Comment by davidanthoff** [comment]
Yes, this might just be a documentation problem.
