### ISSUE TITLE
Plans for updating packages?

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataStreams.jl#39]
Are there any plans for updating packages to the overhauled version?  I'd like to update my package [Estuaries.jl](https://github.com/ExpandingMan/Estuaries.jl) and [Feather.jl](https://github.com/JuliaStats/Feather.jl), but I'm hesitant to do anything before getting a little more feedback on where we are.  Thanks.

**Comment by quinnj** [comment]
Sorry for the slow response here; packages should feel free to update. Feather.jl, CSV.jl, SQLite.jl, DataFrames.jl, and ODBC.jl have all been updated so that current master uses the new DataStreams API. Tags have not been released yet as we're waiting on doing a new tag for DataFrames.jl. Definitely happy to help however I can in making updates.

**Comment by quinnj** [comment]
I'll be working on another round of updates for 0.6/0.7 over the next week.
