### ISSUE TITLE
NamedTuple methods not being created

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/DataStreams.jl#41]
I'm trying to do some work on the new `Nulls` branch of Feather and am running into an issue where the `NamedTuple` constructor isn't getting defined (it is used in Feather).  I'm not sure why DataStreams looks for it in `Core`.  Is this a 0.7 thing?

**Comment by quinnj** [comment]
`Core.NamedTuple` will be defined once https://github.com/JuliaLang/julia/pull/22194 is merged. DataStreams has it correctly version-fenced, but I've yet to update SQLite or Feather. I've updated the ODBC `jq/gangy` branch, and merged `jq/gangy` into CSV master, which is where I'm working this week. My goal is to get CSV.jl all cleaned up and ready to tag, then move on to SQLite (which will be fast), then move on to Feather. There's currently some gnarly work to figure out w/ FlatBuffers.jl on 0.7 and its heavy macro usage, so I've been putting it off a bit. 

Feel free to take a stab at things, but just be aware that most of the `jq/gangy` branches across the DataStreams packages were developed on the `jb/namedtuple` branch off of Julia master, so you'll definitely run into issues if you're not also building that branch.

Alternatively, you could wait about a week and I think I'll have everything cleaned up and merged to master in all those repos. Honestly, the highest priority right now is getting DataFrames all cleaned up and ready to tag, since all the DataStreams packages are downstream (i.e. we can't tag them until DataFrames gets a new tag). We've burned through 100+ issues/PRs in the last week for DataFrames, but there's still some cleanup left to do.

**Comment by ExpandingMan** [comment]
Hm. Ok I'll see what I can do.  For now I might make my own branch of DataStreams that uses the NamedTuples package.

A big priority for me is adding "random access" to Feather, in which one can load individual fields without loading entire columns.  I have an old [PR](https://github.com/JuliaStats/Feather.jl/pull/45) which did this and am now working on an update for Nulls and the new version of DataStreams.

Thanks for all your efforts.

**Comment by quinnj** [comment]
I'm not sure what using the NamedTuples package would get you; NamedTuples were only used as a kind of "default sink" for a little bit, but really isn't necessary. Just change anything from NamedTuple to DataFrame and it should work just fine (assuming you're using current DataFrames master).

For Feather random access, I would just define the appropriate `getindex` methods on `Feather.Source`; that shouldn't be very hard to do at all.

**Comment by ExpandingMan** [comment]
Oh, I wasn't sure that was all it was doing.  Ok, I'll try making a feather branch that uses DataFrames as the default sink.

Also, unless I'm completely missing something.  There is a little more that needs to be done in order to unload individual fields, but I've done this a while ago.  I've also set up `Data.streamfrom` for `Data.field` to do random access.
